config/routes.rb
Rails.application.routes.draw do
  get 'campsite_like/create'
  get 'campsite_like/destroy'
  get 'relationships/followings'
  get 'relationships/followers'
  resources :campsites
  resources :posts do
    collection do
      get "search"
      # => "searches#search"
      # get "search/result" => "search#result"
    end
  end
  get "/" => "home#top"
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
    }
  resources :campsites do
    resource :campsite_likes, only: [:index, :create, :destroy]
  end
  get "campsites/:campsite_id/campsite_likes" => "campsite_likes#index"
  resources :posts do
    resource :likes, only: [:index, :create, :destroy]
  end
  get "posts/:post_id/likes" => "likes#index"
  resources :users, only: [:show, :edit, :update, :destroy]
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # get "search" => "searches#search"
  # get "search/result" => "search#result"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image_name, ImageUploader
    belongs_to :user
    has_many :likes, dependent: :destroy

    def user
        return User.find_by(id:self.user_id)
    end

    def liked_by?(user)
        self.likes.exists?(user_id: user.id)
    end

    # def likes_to?(post)
    #     Like.exists?(user_id: this.id, post_id: post.id)
    # end

    # 検索機能

    def self.search(search)
        if search
          where(["title LIKE? OR content LIKE?", "%#{search}%", "%#{search}%"])
        else
          Post.all
        end
      end

    # def self.looks(search, word)
    #     if search == "perfect_match"
    #         @post = Post.where("title LIKE?", "#{word}")
    #     elsif search == "forward_match"
    #         @post = Post.where("title LIKE?","#{word}%")
    #     elsif search == "backward_match"
    #         @post = Post.where("title LIKE?","%#{word}")
    #     elsif search == "partial_match"
    #         @post = Post.where("title LIKE?","%#{word}%")
    #     else
    #         @post = Post.all
    #     end
    # end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
    @post = Post.new
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find_by(id:params[:id])
    @this_user_posts = Post.where(user_id: @post.user.id)
    @user = @post.user
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    @posts = Post.search(params[:keyword])
  end

  # def result
  #   @posts = Post.search(params[:keyword])
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :campsite_id, :image_name)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
</div>

app/views/posts/edit.html.erb
    <%= form_with model: @post do |form| %>
      <h1>投稿編集</h1>
      <p>タイトル</p>
        <%= form.text_field :title %>
      <p>投稿内容</p>
        <%= form.text_field :content %>
        <%= render "form", post: @post %>
      <p>画像投稿</p>
        <%= form.file_field :image_name %>

        <%
=begin%>
 <% if @post.image_name? %>
          <div class="content-image">
            <%= image_tag @post.image_name.thumb.url  %>
          </div>
        <% else %>
          <div class="content-image">
            <%= image_tag "/no-image.png", class:"post_image" %>
          </div>
        <% end %>  
<%
=end%>

        <script type="text/javascript">
  $(function() {
    function readURL(input) {
        if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
    $('#img_prev').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
        }
    }
    $("#user_img").change(function(){
        readURL(this);
    });
  });
</script>
      <p>キャンプ場名</p>
        <%= form.text_field :campsite_id %>
      <%= form.submit "投稿する" %>
    <% end %>

<!--%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div -->

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>


<!-- ここから_form.html.erbの内容 -->


<%= form_with(model: @post) do |form| %>
  <% if @post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <!-- %= form.submit % -->
  </div>
<% end %>
<!--ここから更新ーーーーーーーーーーーーーーーーーーーー-->

<div class="title-content big-bg">
  <div class="wrapper">
    <h2>POSTS</h2>
    <p><%= link_to "新規投稿", new_post_path, class: "button"%></p>


  </div><!-- /.wrapper -->
</div><!--/.title-content-->

<div id="main-contents" class="wrapper">
  <div class="tanomu">
    <article>

    <!--検索機能 -->

    
      <%= form_with url: search_posts_path, local: true, method: :get do |form| %>
        <div class="search-wrapper wrapper">
          <div><%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-box"%></div>
          <!-- %= form.select :range, options_for_select([[:投稿を検索],[:キャンプ場を検索]]) % -->
          <!--%= form.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) % -->
          <div><%= form.submit "検索", disable_with: 'searching...', class: "search-submit"%></div>
        </div>
      <% end %>




      <div class="wrapper grid">
        <% @posts.each do |post| %>
        <div class="item">
          <% if post.image_name? %>
            <%= link_to post_path(post) do %>
              <%=  image_tag post.image_name.thumb.url, class: "item-image" %>
            <% end %>
          <% else %>
            <%= link_to post_path(post) do %>
              <%= image_tag "/no-image.png", class:"item-image" %>
            <% end %>
          <% end %> 
          <%= link_to post.title, post_path(post), class: "item-title"%>

          <div class="likes-button" style="float: right; margin-top: 10px;">
            <% if current_user %>
              <% if post.liked_by?(current_user) %>
                <%= button_to "/posts/#{post.id}/likes", method: :delete do %>
                  <i class="fa-solid fa-heart fa-2x"></i>
                <% end %>
              <% else %>
                <%= button_to "/posts/#{post.id}/likes" do %>
                  <i class="fa-regular fa-heart size fa-2x"></i>
                <% end %>
              <% end %> 
            <% end %>
            <p class="likes-count" style="font-size: 1rem;"><%= link_to post.likes.count, "/posts/#{post.id}/likes" %></p>
          </div><!--/.likes-button-->
        </div>
        <% end %>
      </div><!-- /.grid -->
    </article>

    <aside>
      <h3 class="sub-title">POSTS</h3>
      <ul class="sub-menu">
          <li><a href="#">投稿記事一覧</a></li>
          <li><a href="#">人気の投稿</a></li>
          <li><a href="#">お気に入りの投稿</a></li>
      </ul>

      <h3 class="sub-title">CAMPSITES</h3>
      <ul class="sub-menu">
          <li><a href="#">キャンプ場一覧</a></li>
          <li><a href="#">人気のキャンプ場</a></li>
          <li><a href="#">お気に入りのキャンプ場</a></li>
      </ul>
    </aside>
  </div><!-- /.tanomu-->
</div><!--/.main-contents-->















<%
=begin%>
 
<!-- ここまで -----------------------------------

<div class="container">

  <p class="page-title">Posts</p>

<検索機能 -->

  <!--div class="search-wrapper">
    <%= form_with url: search_path, local: true, method: :get do |form| %>
        <%= form.text_field :word %>
        <%= form.select :range, options_for_select([[:post],[:campsite]]) %>
        <%= form.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
        <%= form.submit "検索", disable_with: 'searching...' %>
    <% end %>
  </div>

  
  <div class="post-new">
  <% if user_signed_in? % >
  <!-- %= form_with model: @post, local: true do |form| % -->
    <!--%= form_with model: @post do |form| %>
      <h1>新規投稿</h1>
      <p>タイトル</p>
        <%= form.text_field :title %>
      <p>投稿内容</p>
        <%= form.text_field :content % -->        
        <!-- %= render "form", post: @post % -->
      <!--p>画像投稿</!--p>
        <%= form.file_field :image_name %>
      <p>キャンプ場名</p>
        <%= form.text_field :campsite_id %>
        <%= form.submit "投稿する" %>
    <% end %>
  <% end %>
  </div>

  <div class="post-contents">
    <% @posts.each do |post| %>
      <div class="post-content">
        <% if post.image_name? %>
          <div class="content-image">
            <%= image_tag post.image_name.thumb.url  %>
          </div>
        <% else %>
          <div class="content-image">
            <%= image_tag "/no-image.png", class:"post_image" %>
          </div>
        <% end %> 


        <div class="content-title">
          <%= link_to post.title, post_path(post) %>
        </div>

        <% if current_user %>
          <% if post.liked_by?(current_user) %>
            <%= button_to "いいね解除", "/posts/#{post.id}/likes", method: :delete %>
          <% else %>
            <%= button_to "いいね！", "/posts/#{post.id}/likes" %>
          <% end %> 
        <% end %>

        <p>いいね数：<%= link_to post.likes.count, "/posts/#{post.id}/likes" %></p>

        <div class="show-content">
          <div>
            <%= post.content %>
          </div>
          <div>
            <%= link_to post.user.name, user_path(post.user) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div -->
 
<%
=end%>

app/views/posts/new.html.erb
<div class="wrapper" id="new-post-page">
  <div class="post-new-body">
    <h1>新規投稿</h1>



    <br>
    <div class="new-post">
    <%= form_with model: @post, local: true do |form| %>
      <div class="post-item">
        <p>タイトル</p>
        <%= form.text_field :title, class: "title-text text-field" %>
      </div>
      <div class="post-item">
        <p>投稿内容</p>
        <%= form.text_field :content, class: "content-text text-field" %>
        <%= render "form", post: @post %>
      </div>
      <div class="post-item">
        <p>画像投稿</p>
        <%= form.file_field :image_name, class: "image-file-field" %>
      </div>
      <div class="post-item">
        <p>キャンプ場名</p>
        <%= form.text_field :campsite_id, class: "campsite-text text-field" %>
      </div>
      <br>
      <%= form.submit "投稿する", class: "submit button" %>
    <% end %>
    </div><!--/.new-post -->
  </div><!--/.new-post-body-->
</div><!--/.new-post-page -->

<div>
  <!-- %= link_to "Back to posts", posts_path % -->
</div>

app/views/posts/search.html.erb
<div id="search-contents" class="wrapper">
  <div class="tanomu">
    <article>

    <!--検索機能 -->

    <h2 class="wrapper-title"><%= "『#{params[:keyword]}』の検索結果"%></h2>
    
    <%= form_with url: search_posts_path, local: true, method: :get do |form| %>
      <div class="search-wrapper wrapper">
        <div><%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-box"%></div>
        <!-- %= form.select :range, options_for_select([[:投稿を検索],[:キャンプ場を検索]]) % -->
        <!--%= form.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) % -->
        <div><%= form.submit "検索", disable_with: 'searching...', class: "search-submit"%></div>
      </div>
    <% end %>

    

    

      <div class="wrapper grid">
        <% @posts.each do |post| %>
        <div class="item">
          <% if post.image_name? %>
            <%= link_to post_path(post) do %>
              <%=  image_tag post.image_name.thumb.url, class: "item-image" %>
            <% end %>
          <% else %>
            <%= link_to post_path(post) do %>
              <%= image_tag "/no-image.png", class:"item-image" %>
            <% end %>
          <% end %> 
          <%= link_to post.title, post_path(post), class: "item-title"%>
        </div>
        <% end %>
      </div><!-- /.grid -->
    </article>

    <aside>
      <h3 class="sub-title">POSTS</h3>
      <ul class="sub-menu">
          <li><a href="#">投稿記事一覧</a></li>
          <li><a href="#">人気の投稿</a></li>
          <li><a href="#">お気に入りの投稿</a></li>
      </ul>

      <h3 class="sub-title">CAMPSITES</h3>
      <ul class="sub-menu">
          <li><a href="#">キャンプ場一覧</a></li>
          <li><a href="#">人気のキャンプ場</a></li>
          <li><a href="#">お気に入りのキャンプ場</a></li>
      </ul>
    </aside>
  </div><!-- /.tanomu-->
</div><!--/.main-contents-->

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>
<div id="post-show-page" class="wrapper">

<article>
<div class="show-post-content wrapper-in-article">
  <% if @post.image_name? %>
    <div class="show-content-image">
      <%= image_tag @post.image_name.url, class:"show-post-image"  %>
    </div>
  <% else %>
    <div class="show-content-image">
      <%= image_tag "/no-image.png", class:"show-post-image" %>
    </div>
  <% end %>

  <div class="post-infomation">
    <div  class="show-item-title">
      <h2><%= @post.title %></h2>
      <p><%= time_ago_in_words(@post.created_at) %>前</p>
    </div>
    

    <div class="likes-button">
      <% if current_user %>
        <% if @post.liked_by?(current_user) %>
          <%= button_to "/posts/#{@post.id}/likes", method: :delete do %>
            <i class="fa-solid fa-heart size"></i>
          <% end %>
        <% else %>
          <%= button_to "/posts/#{@post.id}/likes" do %>
            <i class="fa-regular fa-heart size"></i>
          <% end %>
        <% end %> 
      <% end %>
      <p class="likes-count"><%= link_to @post.likes.count, "/posts/#{@post.id}/likes" %></p>
    </div><!--/.likes-button-->
  </div><!--/.post-infomation-->
    <div class="show-content">
      <p class="post-content"><%= @post.content %></p>
    </div>
    <div class="show-user-name">
      
    </div>

    <% if current_user %>
      <% if @post.user.name == current_user.name %>
        <div class="current_user_only_button">
          <%= button_to "投稿を編集する", edit_post_path, method: :get, class: "button" %>
          <%= button_to "投稿を削除する", post_path, method: :delete, class: "destroy-button" %>
        </div>
      <% end %>
    <% end %>
  
</div>


<!--ユーザーの他の投稿ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー-->
  <% if current_user %>
    <% if @post.user.id != current_user.id %>
    <h1 class="other-user-post-title">このユーザーの他の投稿</h1>
    <div class="grid wrapper-in-article">
        <% @this_user_posts.each.each do |post| %>
        <div class="item">
          <% if post.image_name? %>
              <%= image_tag post.image_name.thumb.url, class: "item-image" %>
          <% else %>
              <%= image_tag "/no-image.png", class:"item-image" %>
          <% end %> 
          <%= link_to post.title, post_path(post), class: "item-title"%>
        </div>
        <% end %>
      </div><!-- /.grid -->
    <%
=begin%>
 <% @this_user_posts.each do |post| %>
      <% if @post.id != post.id %>
        <div class="post-content">
          <% if post.image_name? %>
            <div class="content-image">
              <%= image_tag post.image_name.thumb.url  %>
            </div>
          <% else %>
            <div class="content-image">
              <%= image_tag "/no-image.png", class:"post_image" %>
            </div>
            
          <% end %>

          <div class="content-title">
            <%= link_to post.title, post_path(post) %>
          </div>
          <div>
            <%= post.content %>
          </div>
        </div>
        <% end %>
    <% end %> 
<%
=end%>
  <% end %>
<% end %> 
</article>

<!--投稿したユーザーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー-->
<aside class="user-aside">
  <h2>投稿したユーザー</h2>
  <% if @user.image_name? %>
      <div class="user-content-image">
      <%= image_tag @user.image_name.thumb.url, class: "user-image"  %>
      </div>
  <% else %>
      <div class="user-content-image">
      <%= image_tag "/no-image.png", class:"user_image" %>
      </div>
  <% end %>

  <div class="user-info">
  <% if @user.id == current_user.id %>
      <p>ユーザー氏名：<%= link_to @post.user.name, user_path(@post.user) %></p>
  <% end %>
  <br>
      <p>ニックネーム：<%= link_to @post.user.nickname, user_path(@post.user) %></p>
      <p>自己紹介
      <br><%= @user.comment %></p>
      <p>フォロー数　　　:　<%= link_to @user.followings.count, user_followings_path(@user) %></p>
      <p><td>フォロワー数　　:　<%= link_to @user.followers.count, user_followers_path(@user) %></p>

      <% if @user.name == current_user.name %>
          <div class="user-button"><%= link_to "ユーザー情報編集", edit_user_registration_path, class: "user-info-button" %></div>
      <% elsif current_user.following?(@user) %>
          <div class="user-button"><%= button_to "フォロー解除", user_relationships_path(@user.id), method: :delete, class: "user-info-button" %></div>
      <% else %>
          <div class="user-button"><%= button_to "フォローする", user_relationships_path(@user.id), class: "user-info-button" %></div>
      <% end %>
  </div><!--/.user-info-->
</aside>

</div>
<%= link_to "投稿一覧に戻る", posts_path %>