config/routes.rb
Rails.application.routes.draw do
  get 'campsite_like/create'
  get 'campsite_like/destroy'
  get 'relationships/followings'
  get 'relationships/followers'
  resources :campsites
  resources :posts do
    collection do
      get "search"
      # => "searches#search"
      # get "search/result" => "search#result"
    end
  end
  get "/" => "home#top"
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
    }
  resources :campsites do
    resource :campsite_likes, only: [:index, :create, :destroy]
  end
  get "campsites/:campsite_id/campsite_likes" => "campsite_likes#index"
  resources :posts do
    resource :likes, only: [:index, :create, :destroy]
  end
  get "posts/:post_id/likes" => "likes#index"
  resources :users, only: [:show, :edit, :update, :destroy]
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # get "search" => "searches#search"
  # get "search/result" => "search#result"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/campsite.rb
class Campsite < ApplicationRecord
    mount_uploader :image_name, ImageUploader

    has_many :campsite_likes, dependent: :destroy 

    # def self.looks(search, word)
    #     if search == "perfect_match"
    #         @campsite = Campsite.where("name LIKE?","#{word}")
    #     elsif search == "forward_match"
    #         @campsite = Campsite.where("name LIKE?","#{word}%")
    #     elsif search == "backward_match"
    #         @campsite = Campsite.where("name LIKE?","%#{word}")
    #     elsif search == "partial_match"
    #         @campsite = Campsite.where("name LIKE?","%#{word}%")
    #     else
    #         @campsite = Campsite.all
    #     end
    # end

    def is_liked_by?(user)
        self.campsite_likes.exists?(user_id: user.id)
    end
end

app/controllers/campsites_controller.rb
class CampsitesController < ApplicationController
  before_action :set_campsite, only: %i[ show edit update destroy ]

  # GET /campsites or /campsites.json
  def index
    @campsites = Campsite.all
  end

  # GET /campsites/1 or /campsites/1.json
  def show
  end

  # GET /campsites/new
  def new
    @campsite = Campsite.new
  end

  # GET /campsites/1/edit
  def edit
  end

  # POST /campsites or /campsites.json
  def create
    @campsite = Campsite.new(campsite_params)

    respond_to do |format|
      if @campsite.save
        format.html { redirect_to campsite_url(@campsite), notice: "Campsite was successfully created." }
        format.json { render :show, status: :created, location: @campsite }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @campsite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campsites/1 or /campsites/1.json
  def update
    respond_to do |format|
      if @campsite.update(campsite_params)
        format.html { redirect_to campsite_url(@campsite), notice: "Campsite was successfully updated." }
        format.json { render :show, status: :ok, location: @campsite }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @campsite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campsites/1 or /campsites/1.json
  def destroy
    @campsite.destroy

    respond_to do |format|
      format.html { redirect_to campsites_url, notice: "Campsite was successfully destroyed." }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campsite
      @campsite = Campsite.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def campsite_params
      # params.fetch(:campsite, {})
      params.require(:campsite).permit(:name, :prefecture, :municipalitie, :address, :introduction, :image_name )
    end
end

app/helpers/campsites_helper.rb
module CampsitesHelper
end

app/views/campsites/_campsite.html.erb
<div id="<%= dom_id campsite %>">
</div>

app/views/campsites/_form.html.erb
<%= form_with(model: campsite) do |form| %>
  <% if campsite.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(campsite.errors.count, "error") %> prohibited this campsite from being saved:</h2>

      <ul>
        <% campsite.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/campsites/edit.html.erb
<h1>Editing campsite</h1>

<%= form_with model: @campsite do |form| %>
  <p>キャンプ場名</p>
  <%= form.text_field :name %>
  <p>都道府県</p>
  <%= form.text_field :prefecture %>
  <p>市区町村</p>
  <%= form.text_field :municipalitie %>
  <p>以降の住所</p>
  <%= form.text_field :address %>
  <p>キャンプ場の紹介</p>
  <%= form.text_field :introduction %>
  <p>画像投稿</p>
  <%= form.file_field :image_name %>
  <%= form.submit "更新する" %>
<% end %>

<!-- %= render "form", campsite: @campsite % -->

<br>

<div>
  <%= link_to "キャンプ場の詳細画面に戻る", @campsite %> |
  <%= link_to "キャンプ場一覧に戻る", campsites_path %>
</div>

app/views/campsites/index.html.erb
<head>
  <link rel="stylesheet" href="app/assets/stylesheets/campsite.scss">
</head>
<!--ここから更新ーーーーーーーーーーーーーーーーーーーー-->

<div class="campsite-title-content big-bg">
  <div class="wrapper">
    <h2>CAMPSITES</h2>
    <p>キャンプ場検索</p>
  </div>
</div><!--/.title-content-->

<div class="main-contents wrapper">
  <div class="tanomu">
    <article>
    
      <div class="wrapper grid">
        <% @campsites.each do |campsite| %>
        <div class="item">
          <% if campsite.image_name.present? %>
              <%= image_tag campsite.image_name.thumb.url, class: "item-image" %>
          <% else %>
              <%= image_tag "/no-image.png", class:"item-image" %>
          <% end %> 
          <%= link_to campsite.name, campsite_path(campsite), class: "item-title"%>
        </div>
        
        
        
        <% end %>
        
    </div><!-- /.grid -->
    </article>

    <aside>
      <h3 class="sub-title">POSTS</h3>
      <ul class="sub-menu">
          <li><a href="#">投稿記事一覧</a></li>
          <li><a href="#">人気の投稿</a></li>
          <li><a href="#">お気に入りの投稿</a></li>
      </ul>

      <h3 class="sub-title">CAMPSITES</h3>
      <ul class="sub-menu">
          <li><a href="#">キャンプ場一覧</a></li>
          <li><a href="#">人気のキャンプ場</a></li>
          <li><a href="#">お気に入りのキャンプ場</a></li>
      </ul>
    </aside>
  </div>
</div><!--/.main-contents-->


<%
=begin%>
 















<!--h1>Campsites</!--h1>

<%= form_with url: search_path, local: true, method: :get do |form| %>
    <%= form.text_field :word %>
    <%= form.select :range, options_for_select([[:campsite],[:campsite]]) %>
    <%= form.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
    <%= form.submit "検索", disable_with: 'searching...' %>
<% end %>

  <div id="campsites">
    <% @campsites.each do |campsite| %>
      <div class="campsite-content"> 

        <% if campsite.image_name %>
          <div class="content-image">
            <%= image_tag campsite.image_name.thumb.url  %>
          </div>
        <% else %>
          <div class="content-image">
            <%= image_tag "/no-image.png", class:"campsite_image" %>
          </div>
        <% end %> 

        <div class="content-title">
          <%= link_to campsite.name, campsite_path(campsite) %>
        </div>
        <div>
          <%= campsite.prefecture + campsite.municipalitie + campsite.address %>
        </div>
        <div>
          <% if campsite.image_name.present? %>
            <%= image_tag campsite.image_name.thumb.url  %>
          <% else %>
            <%= image_tag "no-image.png", size: '200x200'%>
          <% end %>
        </div>
        <div>
          <%= campsite.introduction %>
        </div -->

        <!--お気に入り機能>
        <% if current_user %>
          <% if campsite.is_liked_by?(current_user) %>
            <%= button_to "お気に入り解除", "/campsites/#{campsite.id}/campsite_likes", method: :delete %>
          <% else %>
            <%= button_to "お気に入り登録", "/campsites/#{campsite.id}/campsite_likes" %>
          <% end %> 
        <% end %>
        
      </div>
    <% end %>
  </div>

  <br>
  <%= link_to "キャンプ場を登録する", new_campsite_path %>

  <p style="color: green"><%= notice %></p>

  <div id="campsites">
  <% @campsites.each do |campsite| %>
    <%= render campsite %>
    <p -->
      <!-- %= link_to "Show this campsite", campsite % -->
    <!--/p>
  <% end %>
</div --> 
<%
=end%>

app/views/campsites/new.html.erb
<h1>キャンプ場登録</h1>

<%= form_with model: @campsite, local: true do |form| %>
  <p>キャンプ場名</p>
  <%= form.text_field :name %>
  <p>都道府県</p>
  <%= form.text_field :prefecture %>
  <p>市区町村</p>
  <%= form.text_field :municipalitie %>
  <p>以降の住所</p>
  <%= form.text_field :address %>
  <p>キャンプ場の紹介</p>
  <%= form.text_field :introduction %>
  <p>画像投稿</p>
  <%= form.file_field :image_name %>
  <%= form.submit "投稿する" %>
<% end %>

<!-- %= render "form", campsite: @campsite % -->

<br>

<div>
  <%= link_to "Back to campsites", campsites_path %>
</div>

app/views/campsites/show.html.erb
<h1>campsite</h1>

<!-- %= image_tag @campsite.image_name % -->
<% if @campsite.image_name.present? %>
  <%= image_tag @campsite.image_name.thumb.url  %>
<% else %>
  <%= image_tag "no-image.png" %>
<% end %>
<%= @campsite.name %>
<%= @campsite.prefecture + @campsite.municipalitie + @campsite.address %>
<%= @campsite.introduction %>

<% if current_user %>
    <%= link_to "編集", edit_campsite_path %>
<% end %>





<p style="color: green"><%= notice %></p>

<%= render @campsite %>

<div>

  <%= link_to "キャンプ場一覧に戻る", campsites_path %>

  <%= button_to "キャンプ場を削除する", @campsite, method: :delete %>
</div>