config/routes.rb
Rails.application.routes.draw do
  get 'campsite_like/create'
  get 'campsite_like/destroy'
  get 'relationships/followings'
  get 'relationships/followers'
  resources :campsites
  resources :posts do
    collection do
      get "search"
      # => "searches#search"
      # get "search/result" => "search#result"
    end
  end
  get "/" => "home#top"
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
    }
  resources :campsites do
    resource :campsite_likes, only: [:index, :create, :destroy]
  end
  get "campsites/:campsite_id/campsite_likes" => "campsite_likes#index"
  resources :posts do
    resource :likes, only: [:index, :create, :destroy]
  end
  get "posts/:post_id/likes" => "likes#index"
  resources :users, only: [:show, :edit, :update, :destroy]
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # get "search" => "searches#search"
  # get "search/result" => "search#result"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CampApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- JavaScript導入 -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css" -->
    <script src="https://kit.fontawesome.com/fb8319747b.js" crossorigin="anonymous"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css">
  </head>

  <body>
  <div class="title-header">
      <div class="page-header wrapper">
            <!--i class="fa-solid fa-campground fa-2x"></!--i-->
        <%= link_to "/" do %>
          <h2 class="site-title-logo"><i class="fa-solid fa-campground"></i>campsite title</h2>
        <% end %>
        <nav>
            <ul class="main-nav">
                <li><%= link_to "Posts", posts_path %></li>
                <li><%= link_to "Campsites", campsites_path %></li>
                <% if current_user %>
                  <li><%= link_to "My Page", user_path(current_user)%></li>
                <% end %>
            </ul>
        </nav>
      </div>
    </div><!--page-header-->
  </div>

    <div class="main-content">
        <%= yield %>
    </div><!--./main-contents-->

    <footer>
        <div class="wrapper">
            <p><small>&copy; 2022 sakata</small></p>
        </div>
    </footer>
  </body>
</html>